import Head from 'next/head'
import {Layout} from '@/components/Layout'
import Image from 'next/image'
import profilePic from "../../public/images/profile/comic-pic.png"
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import {AnimatedText} from '@/components/AnimatedText'
import {motion} from "framer-motion"
import Link from 'next/link'
import { LinkArrow } from '../components/Icons'
import HireMe from '../components/HireMe'

export default function Home() {
  return (
    <>
      <Head>
        <title>Farhan's Portfolio Homepage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0 mt-0'>
          <div className="flex items-center justify-between w-full">
            <div className='w-5/12'>
              <Image  src={profilePic} alt={'_blank'} className='w-9/10 h-auto' />
            </div>
            <div className='w-7/12 h-full flex flex-col item-center self-center'>
              <AnimatedText text="Turning Vision Into Reality With Code And Design" fontSize='60px' textAlign='left'/>

              <p className='my-4 text-base font-medium items-start'>
                <span style={{ display: 'block' }}>• As a full-stack developer, I am dedicated to turning ideas into innovative web applications. </span>
                <span style={{ display: 'block' }}>• As a data analyst, I can also cater to your data insight needs. </span>
                <span style={{ display: 'block' }}>• Explore my latest projects, showcasing my expertise in development and analysis. </span>
              </p>

              <div className='flex items-center self-start mt-2'>
                <Link href="/dummy.pdf" download={true} target={"_blank"} className='flex items-start bg-dark p-2.5 px-6 rounded-lg text-lg hover:bg-light mx-2' style={{color: 'white'}}> 
                  Resume <LinkArrow className='w-5 ml-1'/>
                </Link>
                
                <Link href="mailto:developer.dmitri@gmail.com" target={"_blank"} className='flex items-start bg-dark p-2.5 px-6 rounded-lg text-lg hover:bg-light mx-2' style={{color: 'white'}}> 
                  Contact 
                </Link>
              </div>
            </div>
          </div>
        </Layout >
        
        <HireMe />
        <div className='absolute right-8 botton-8 inline-block w-24'>
          <Image src={lightBulb} className='w-full h-auto' />
        </div>
      </main>
    </>
  )
}
