import Head from 'next/head'
import {Layout} from '@/organisms/Layout'
import Image from 'next/image'
import profilePic from "../../public/images/profile/comic-pic.png"
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import {AnimatedText} from '@/molecules/AnimatedText'
import {motion} from "framer-motion"
import Link from 'next/link'
import { LinkArrow } from '../atoms/Icons'
import HireMe from '../molecules/HireMe'
import TransitionEffect from "@/atoms/TransitionEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Farhan&apos;s Portfolio Homepage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>


      <TransitionEffect />
      <article
        className={`flex min-h-screen items-center text-dark dark:text-light sm:items-start`}
      >
        <Layout className="!pt-0 md:!pt-16 sm:!pt-16">
          <div className="flex w-full items-start justify-between md:flex-col">
            <div className="w-1/2 lg:hidden md:inline-block md:w-full">
              <Image
                src={profilePic}
                alt="CodeBucks"
                className="h-auto w-full"
                sizes="100vw"
                priority
              />
            </div>

            <div className="flex w-1/2 flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Turning vision into reality with code and design."
                className="!text-left !text-6xl xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />

              <p className="my-4 text-base font-medium md:text-sm sm:!text-xs">
                <span style={{ display: 'block', fontSize: '18px' }}>• Data analyst skilled in visualization, machine learning, and automated pipelines. </span>
                <br />
                <span style={{ display: 'block', fontSize: '18px' }}>• Full-stack developer creating innovative web applications with React, Node.js, and Next.js. </span>
                <br />
                <span style={{ display: 'block', fontSize: '18px' }}>• Dive into my latest projects, showcasing my abilities development and data science and deliver impactful solutions. </span>
              </p>

              <div className="mt-2 flex items-center self-start lg:self-center">
                <Link href="https://drive.google.com/file/d/18z01diH5sT2Ie95nq8TIQv0cSwV3ZmOM/view?usp=share_link" download={true} target={"_blank"} className='flex items-start bg-dark p-2.5 px-6 text-light rounded-lg text-lg hover:text-dark hover:bg-light mx-2'> 
                  Resume &#x279A;
                </Link>
                
                <Link href="mailto:developer.dmitri@gmail.com" target={"_blank"} className='flex items-start bg-dark p-2.5 px-6 rounded-lg text-lg hover:bg-light hover:text-dark  text-light mx-2'>
                  Contact 
                </Link>
              </div>
            </div>
          </div>
        </Layout >
        
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image src={lightBulb} alt={"_blank"} className='w-full h-auto' />
        </div>
      </article>
    </>
  )
}
